---
# This Play will print a debug message on the host.
- name: Play that prints a debug message
  hosts: all
  connection: local
  vars:
    person: Mani

  tasks:
    - ansible.builtin.debug:
        msg: Hello there {{ person }}!
